export const UI_MESSAGES=Object.freeze({
  es:{
    appName:'Evidencia Jurídica',tagline:'Consulta documentos y normas con evidencia verificable.',demoBadge:'Demostración · Colombia',
    nav:{research:'Investigación',documents:'Documentos',evidence:'Evidencia'},
    actions:{law:'Consultar legislación',document:'Analizar un documento',ask:'Consultar',remove:'Eliminar',reindex:'Reindexar',inspect:'Ver pasajes',close:'Cerrar',changeArea:'Cambiar área',newQuery:'Nueva consulta',showMore:'Mostrar más fuentes',showLess:'Mostrar menos fuentes'},
    landing:{eyebrow:'Investigación jurídica basada en evidencia',title:'Trabaja desde la fuente, no desde una respuesta opaca.',body:'Consulta un corpus jurídico colombiano gobernado y contrástalo con documentos privados procesados localmente en esta sesión.',areaTitle:'¿En qué área estás trabajando?',areaHelp:'El área orienta la búsqueda; no es una clasificación jurídica rígida.'},
    domains:{general:'General',civil:'Derecho civil',familia:'Derecho de familia',laboral:'Derecho laboral',penal:'Derecho penal',notarial:'Derecho notarial',constitucional:'Derecho constitucional',unsure:'No estoy seguro'},
    workspace:{corpus:'Corpus',corpusCount:'Fuentes normativas',documents:'Documentos privados',noDocuments:'Aún no has agregado documentos.',question:'Consulta',questionHelp:'Formula una pregunta concreta. La respuesta solo usará evidencia recuperada.',placeholder:'Ej.: ¿Qué elementos exige la norma disponible para un contrato de trabajo?',sources:'Fuentes y evidencia',noAnswer:'Las fuentes aparecerán aquí después de una consulta.',emptyAnswer:'Haz una consulta para ver respuesta, fundamento y evidencia.',area:'Área de búsqueda',publicCorpus:'Corpus jurídico público',privateDocs:'Documentos de esta sesión'},
    upload:{title:'Analizar un documento',body:'PDF con capa de texto, DOCX o TXT. Máximo 10 MB.',choose:'Seleccionar archivo',local:'Procesamiento local en esta sesión',noTraining:'Sin ruta de entrenamiento ni telemetría de contenido',retention:'El texto y los vectores se conservan solo en memoria de sesión.',warning:'Para esta demostración, no cargues información confidencial de clientes.',stages:{preparing:'Preparando documento',reading:'Leyendo texto',organizing:'Organizando secciones',search_ready:'Preparando búsqueda',ready:'Listo para consultar'},ocr:'OCR no está implementado; los PDF sin capa de texto no se pueden indexar.'},
    evidence:{law:'Norma',user:'Documento del usuario',article:'Artículo / sección',authority:'Autoridad',verified:'Verificado',version:'Versión',source:'Abrir fuente oficial',historical:'Vigencia actual no resuelta',crossDomain:'Relevante fuera del área preferida',excerpt:'Pasaje exacto',score:'Diagnóstico de recuperación'},
    answer:{supported:'Respuesta sustentada',insufficient:'Evidencia insuficiente'},
    status:{loading:'Preparando corpus…',ready:'Corpus listo',error:'No se pudo completar la operación.',deleted:'Documento eliminado de la sesión.',reindexed:'Documento reindexado.',uploaded:'Documento listo para consultar.'},
    diagnostics:{title:'Diagnóstico avanzado',model:'Modelo local',chunks:'Fragmentos',hash:'SHA-256',scope:'Ámbito',scores:'Puntuaciones'},
    privacy:{title:'Privacidad de la demostración',body:'Los documentos se procesan localmente y solo permanecen en memoria de esta sesión. Al eliminarlos se borran texto, fragmentos y vectores; puede quedar un registro no textual de eliminación hasta recargar la página.'},
    language:'Idioma',skip:'Saltar al contenido',footer:'Herramienta de investigación basada en evidencia. No sustituye el juicio profesional de un abogado o notario colombiano.'
  },
  en:{
    appName:'Legal Evidence',tagline:'Query documents and rules with verifiable evidence.',demoBadge:'Demo · Colombia',
    nav:{research:'Research',documents:'Documents',evidence:'Evidence'},
    actions:{law:'Research legislation',document:'Analyze a document',ask:'Research',remove:'Remove',reindex:'Re-index',inspect:'View passages',close:'Close',changeArea:'Change area',newQuery:'New query',showMore:'Show more sources',showLess:'Show fewer sources'},
    landing:{eyebrow:'Evidence-based legal research',title:'Work from the source, not from an opaque answer.',body:'Search a governed Colombian legal corpus and compare it with private documents processed locally in this session.',areaTitle:'Which area are you working in?',areaHelp:'The area guides retrieval; it is not a rigid legal classification.'},
    domains:{general:'General',civil:'Civil law',familia:'Family law',laboral:'Labor law',penal:'Criminal law',notarial:'Notarial law',constitucional:'Constitutional law',unsure:'Not sure'},
    workspace:{corpus:'Corpus',corpusCount:'Legal sources',documents:'Private documents',noDocuments:'No documents added yet.',question:'Research question',questionHelp:'Ask a specific question. The answer will use retrieved evidence only.',placeholder:'Example: What elements does the available rule require for an employment contract?',sources:'Sources and evidence',noAnswer:'Sources will appear here after a query.',emptyAnswer:'Run a query to see the answer, basis and evidence.',area:'Research area',publicCorpus:'Public legal corpus',privateDocs:'Documents in this session'},
    upload:{title:'Analyze a document',body:'Text-layer PDF, DOCX or TXT. Maximum 10 MB.',choose:'Select file',local:'Processed locally in this session',noTraining:'No training path or content telemetry',retention:'Text and vectors remain in session memory only.',warning:'For this demonstration, do not upload confidential client information.',stages:{preparing:'Preparing document',reading:'Reading text',organizing:'Organizing sections',search_ready:'Preparing search',ready:'Ready to research'},ocr:'OCR is not implemented; PDFs without a text layer cannot be indexed.'},
    evidence:{law:'Legal source',user:'User document',article:'Article / section',authority:'Authority',verified:'Verified',version:'Version',source:'Open official source',historical:'Current validity unresolved',crossDomain:'Relevant outside preferred area',excerpt:'Exact passage',score:'Retrieval diagnostics'},
    answer:{supported:'Evidence-supported answer',insufficient:'Insufficient evidence'},
    status:{loading:'Preparing corpus…',ready:'Corpus ready',error:'The operation could not be completed.',deleted:'Document removed from this session.',reindexed:'Document re-indexed.',uploaded:'Document ready to research.'},
    diagnostics:{title:'Advanced diagnostics',model:'Local model',chunks:'Chunks',hash:'SHA-256',scope:'Scope',scores:'Scores'},
    privacy:{title:'Demo privacy',body:'Documents are processed locally and remain in session memory only. Removing a document clears its text, chunks and vectors; a non-content deletion record may remain until the page is refreshed.'},
    language:'Language',skip:'Skip to content',footer:'Evidence-based research tool. It does not replace professional judgment by Colombian counsel or a notary.'
  },
  pt:{
    appName:'Evidência Jurídica',tagline:'Consulte documentos e normas com evidência verificável.',demoBadge:'Demonstração · Colômbia',
    nav:{research:'Pesquisa',documents:'Documentos',evidence:'Evidência'},
    actions:{law:'Consultar legislação',document:'Analisar um documento',ask:'Consultar',remove:'Excluir',reindex:'Reindexar',inspect:'Ver trechos',close:'Fechar',changeArea:'Mudar área',newQuery:'Nova consulta',showMore:'Mostrar mais fontes',showLess:'Mostrar menos fontes'},
    landing:{eyebrow:'Pesquisa jurídica baseada em evidências',title:'Trabalhe a partir da fonte, não de uma resposta opaca.',body:'Consulte um corpus jurídico colombiano governado e compare-o com documentos privados processados localmente nesta sessão.',areaTitle:'Em que área você está trabalhando?',areaHelp:'A área orienta a busca; não é uma classificação jurídica rígida.'},
    domains:{general:'Geral',civil:'Direito civil',familia:'Direito de família',laboral:'Direito do trabalho',penal:'Direito penal',notarial:'Direito notarial',constitucional:'Direito constitucional',unsure:'Não tenho certeza'},
    workspace:{corpus:'Corpus',corpusCount:'Fontes normativas',documents:'Documentos privados',noDocuments:'Nenhum documento foi adicionado.',question:'Consulta',questionHelp:'Faça uma pergunta concreta. A resposta usará apenas a evidência recuperada.',placeholder:'Ex.: Quais elementos a norma disponível exige para um contrato de trabalho?',sources:'Fontes e evidências',noAnswer:'As fontes aparecerão aqui após uma consulta.',emptyAnswer:'Faça uma consulta para ver resposta, fundamento e evidência.',area:'Área de pesquisa',publicCorpus:'Corpus jurídico público',privateDocs:'Documentos desta sessão'},
    upload:{title:'Analisar um documento',body:'PDF com camada de texto, DOCX ou TXT. Máximo 10 MB.',choose:'Selecionar arquivo',local:'Processamento local nesta sessão',noTraining:'Sem rota de treinamento nem telemetria de conteúdo',retention:'Texto e vetores permanecem apenas na memória da sessão.',warning:'Para esta demonstração, não envie informações confidenciais de clientes.',stages:{preparing:'Preparando documento',reading:'Lendo texto',organizing:'Organizando seções',search_ready:'Preparando busca',ready:'Pronto para consultar'},ocr:'OCR não está implementado; PDFs sem camada de texto não podem ser indexados.'},
    evidence:{law:'Norma',user:'Documento do usuário',article:'Artigo / seção',authority:'Autoridade',verified:'Verificado',version:'Versão',source:'Abrir fonte oficial',historical:'Vigência atual não resolvida',crossDomain:'Relevante fora da área preferida',excerpt:'Trecho exato',score:'Diagnóstico de recuperação'},
    answer:{supported:'Resposta sustentada',insufficient:'Evidência insuficiente'},
    status:{loading:'Preparando corpus…',ready:'Corpus pronto',error:'Não foi possível concluir a operação.',deleted:'Documento removido da sessão.',reindexed:'Documento reindexado.',uploaded:'Documento pronto para consulta.'},
    diagnostics:{title:'Diagnóstico avançado',model:'Modelo local',chunks:'Fragmentos',hash:'SHA-256',scope:'Escopo',scores:'Pontuações'},
    privacy:{title:'Privacidade da demonstração',body:'Os documentos são processados localmente e permanecem apenas na memória desta sessão. Ao excluir, texto, fragmentos e vetores são removidos; um registro não textual de exclusão pode permanecer até recarregar a página.'},
    language:'Idioma',skip:'Ir para o conteúdo',footer:'Ferramenta de pesquisa baseada em evidências. Não substitui o julgamento profissional de advogado ou notário colombiano.'
  }
});

export const uiMessages=(locale='es')=>UI_MESSAGES[locale]??UI_MESSAGES.es;
export function t(locale,path) { return path.split('.').reduce((v,k)=>v?.[k],uiMessages(locale)) ?? path; }
