export const UI_MESSAGES=Object.freeze({
  es:{
    appName:'Evidencia Jurídica',tagline:'Consulta documentos y normas con evidencia verificable.',demoBadge:'Demostración · Colombia',
    nav:{research:'Investigación',documents:'Documentos',evidence:'Evidencia'},
    actions:{law:'Consultar legislación',document:'Analizar un documento',ask:'Consultar',remove:'Eliminar',reindex:'Reindexar',inspect:'Ver pasajes',close:'Cerrar',changeArea:'Cambiar área',newQuery:'Nueva consulta',showMore:'Mostrar más fuentes',showLess:'Mostrar menos fuentes'},
    landing:{eyebrow:'Investigación jurídica basada en evidencia',title:'Trabaja desde la fuente, no desde una respuesta opaca.',body:'Consulta un corpus jurídico colombiano gobernado y contrástalo con documentos privados procesados localmente en esta sesión.',areaTitle:'¿En qué área estás trabajando?',areaHelp:'El área orienta la búsqueda; no es una clasificación jurídica rígida.'},
    domains:{general:'General',civil:'Derecho civil',familia:'Derecho de familia',laboral:'Derecho laboral',penal:'Derecho penal',notarial:'Derecho notarial',constitucional:'Derecho constitucional',unsure:'No estoy seguro'},
    workspace:{corpus:'Corpus',corpusCount:'Fuentes normativas',documents:'Documentos privados',noDocuments:'Aún no has agregado documentos.',question:'Consulta',questionHelp:'Formula una pregunta concreta. La respuesta solo usará evidencia que supere el control de suficiencia jurídica.',placeholder:'Ej.: ¿Qué elementos exige la norma disponible para un contrato de trabajo?',sources:'Fuentes y evidencia',noAnswer:'Las fuentes aparecerán aquí después de una consulta.',emptyAnswer:'Haz una consulta para ver respuesta, fundamento y evidencia.',area:'Área de búsqueda',publicCorpus:'Corpus jurídico público',privateDocs:'Documentos de esta sesión'},
    coverage:{title:'Alcance de esta demostración',partial:'Corpus parcial',sources:'fuentes oficiales registradas',passages:'pasajes gobernados',jurisprudence:'Jurisprudencia no incluida',fullText:'Sin textos oficiales completos locales',note:'Una respuesta sustentada significa soporte suficiente solo dentro de la evidencia mostrada; no certifica que la investigación jurídica esté completa.'},
    tasks:{title:'Atajos de investigación',help:'Elige una tarea para formular mejor la consulta.',identify:'Identificar norma',proof:'Elementos y prueba',deadline:'Plazo o término',competence:'Competencia judicial',change:'Cambio o versión',jurisprudence:'Jurisprudencia',document:'Comparar documento',examples:{identify:'¿Qué norma disponible regula ',proof:'¿Qué elementos debo probar según la evidencia disponible sobre ',deadline:'¿Cuál es el plazo, término o prescripción aplicable a ',competence:'¿Qué juez o regla de competencia es aplicable a ',change:'¿Qué cambió entre versiones respecto de ',jurisprudence:'¿Qué jurisprudencia oficial interpreta ',document:'Compara mi documento con la regla disponible sobre '}},
    upload:{title:'Analizar un documento',body:'PDF con capa de texto, DOCX o TXT. Máximo 10 MB.',choose:'Seleccionar archivo',local:'Procesamiento local en esta sesión',noTraining:'Sin ruta de entrenamiento ni telemetría de contenido',retention:'El texto y los vectores se conservan solo en memoria de sesión.',warning:'Para esta demostración, no cargues información confidencial de clientes.',stages:{preparing:'Preparando documento',reading:'Leyendo texto',organizing:'Organizando secciones',search_ready:'Preparando búsqueda',ready:'Listo para consultar'},ocr:'OCR no está implementado; los PDF sin capa de texto no se pueden indexar.'},
    evidence:{law:'Norma',user:'Documento del usuario',article:'Artículo / sección',authority:'Autoridad',verified:'Fuente consultada',version:'Versión',source:'Verificar en fuente oficial',historical:'Vigencia actual no resuelta',crossDomain:'Relevante fuera del área preferida',notSupport:'Relacionado; no sustenta la respuesta',excerpt:'Pasaje exacto',score:'Diagnóstico técnico de recuperación · no es confianza jurídica'},
    answer:{supported:'Soporte suficiente en el corpus disponible',supportedDetail:'La conclusión mostrada se limita a la evidencia gobernada citada abajo. Verifica la fuente oficial antes de usarla profesionalmente.',insufficient:'Evidencia insuficiente',insufficientDetail:'El sistema encontró material relacionado, pero no evidencia suficiente para responder con fundamento.',recoveryTitle:'Qué falta para responder',recoveryGeneral:'Reformula la consulta con hechos o una norma más específica, o amplía el corpus con autoridad oficial pertinente.',requirements:{deadline:'Falta una regla expresa de plazo, término, prescripción o caducidad.',competence:'Falta una regla expresa de competencia o fuero aplicable.',remedy:'Falta una regla que establezca el recurso o medio de impugnación.',procedure:'Falta evidencia procedimental que describa el trámite o los pasos aplicables.',change_comparison:'Faltan versiones o afectaciones normativas comparables para afirmar qué cambió.',jurisprudence:'Este corpus todavía no contiene jurisprudencia gobernada para sostener esa respuesta.',current_validity:'No hay certificación de vigencia suficiente para afirmar vigencia actual.',tariff:'Falta una fuente tarifaria o fiscal actual con el valor aplicable.'}},
    status:{loading:'Preparando corpus…',ready:'Corpus listo',error:'No se pudo completar la operación.',deleted:'Documento eliminado de la sesión.',reindexed:'Documento reindexado.',uploaded:'Documento listo para consultar.'},
    diagnostics:{title:'Diagnóstico avanzado',model:'Modelo local',chunks:'Fragmentos',hash:'SHA-256',scope:'Ámbito',scores:'Puntuaciones'},
    privacy:{title:'Privacidad de la demostración',body:'Los documentos se procesan localmente y solo permanecen en memoria de esta sesión. Al eliminarlos se borran texto, fragmentos y vectores; puede quedar un registro no textual de eliminación hasta recargar la página.'},
    language:'Idioma',skip:'Saltar al contenido',footer:'Herramienta de investigación basada en evidencia. No sustituye el juicio profesional de un abogado o notario colombiano.'
  },
  en:{
    appName:'Legal Evidence',tagline:'Query documents and rules with verifiable evidence.',demoBadge:'Demo · Colombia',
    nav:{research:'Research',documents:'Documents',evidence:'Evidence'},
    actions:{law:'Research legislation',document:'Analyze a document',ask:'Research',remove:'Remove',reindex:'Re-index',inspect:'View passages',close:'Close',changeArea:'Change area',newQuery:'New query',showMore:'Show more sources',showLess:'Show fewer sources'},
    landing:{eyebrow:'Evidence-based legal research',title:'Work from the source, not from an opaque answer.',body:'Search a governed Colombian legal corpus and compare it with private documents processed locally in this session.',areaTitle:'Which area are you working in?',areaHelp:'The area guides retrieval; it is not a rigid legal classification.'},
    domains:{general:'General',civil:'Civil law',familia:'Family law',laboral:'Labor law',penal:'Criminal law',notarial:'Notarial law',constitucional:'Constitutional law',unsure:'Not sure'},
    workspace:{corpus:'Corpus',corpusCount:'Legal sources',documents:'Private documents',noDocuments:'No documents added yet.',question:'Research question',questionHelp:'Ask a specific question. The answer will use only evidence that passes the legal-sufficiency check.',placeholder:'Example: What elements does the available rule require for an employment contract?',sources:'Sources and evidence',noAnswer:'Sources will appear here after a query.',emptyAnswer:'Run a query to see the answer, basis and evidence.',area:'Research area',publicCorpus:'Public legal corpus',privateDocs:'Documents in this session'},
    coverage:{title:'Scope of this demonstration',partial:'Partial corpus',sources:'registered official sources',passages:'governed passages',jurisprudence:'Jurisprudence not included',fullText:'No local full official texts',note:'A supported answer means sufficient support only within the evidence shown; it does not certify that legal research is complete.'},
    tasks:{title:'Research shortcuts',help:'Choose a task to structure the query.',identify:'Identify rule',proof:'Elements and proof',deadline:'Deadline or limitation',competence:'Court jurisdiction',change:'Change or version',jurisprudence:'Case law',document:'Compare document',examples:{identify:'Which available rule governs ',proof:'Which elements must be proved in the available evidence about ',deadline:'What deadline or limitation rule applies to ',competence:'Which court or jurisdiction rule applies to ',change:'What changed between versions regarding ',jurisprudence:'Which official case law interprets ',document:'Compare my document with the available rule about '}},
    upload:{title:'Analyze a document',body:'Text-layer PDF, DOCX or TXT. Maximum 10 MB.',choose:'Select file',local:'Processed locally in this session',noTraining:'No training path or content telemetry',retention:'Text and vectors remain in session memory only.',warning:'For this demonstration, do not upload confidential client information.',stages:{preparing:'Preparing document',reading:'Reading text',organizing:'Organizing sections',search_ready:'Preparing search',ready:'Ready to research'},ocr:'OCR is not implemented; PDFs without a text layer cannot be indexed.'},
    evidence:{law:'Legal source',user:'User document',article:'Article / section',authority:'Authority',verified:'Source checked',version:'Version',source:'Verify in official source',historical:'Current validity unresolved',crossDomain:'Relevant outside preferred area',notSupport:'Related; not used to support the answer',excerpt:'Exact passage',score:'Technical retrieval diagnostics · not legal confidence'},
    answer:{supported:'Sufficient support in the available corpus',supportedDetail:'The conclusion shown is limited to the governed evidence cited below. Verify the official source before professional use.',insufficient:'Insufficient evidence',insufficientDetail:'The system found related material but not enough evidence to answer with support.',recoveryTitle:'What is missing',recoveryGeneral:'Refine the question with more specific facts or a rule, or expand the corpus with relevant official authority.',requirements:{deadline:'An explicit deadline, limitation or prescription rule is missing.',competence:'An explicit jurisdiction or venue rule is missing.',remedy:'A rule establishing the remedy or appeal is missing.',procedure:'Procedural evidence describing the applicable steps is missing.',change_comparison:'Comparable versions or normative changes are missing.',jurisprudence:'This corpus does not yet contain governed case law for that answer.',current_validity:'There is not enough certified validity evidence to assert current validity.',tariff:'A current tariff or tax authority stating the applicable value is missing.'}},
    status:{loading:'Preparing corpus…',ready:'Corpus ready',error:'The operation could not be completed.',deleted:'Document removed from this session.',reindexed:'Document re-indexed.',uploaded:'Document ready to research.'},
    diagnostics:{title:'Advanced diagnostics',model:'Local model',chunks:'Chunks',hash:'SHA-256',scope:'Scope',scores:'Scores'},
    privacy:{title:'Demo privacy',body:'Documents are processed locally and remain in session memory only. Removing a document clears its text, chunks and vectors; a non-content deletion record may remain until the page is refreshed.'},
    language:'Language',skip:'Skip to content',footer:'Evidence-based research tool. It does not replace professional judgment by Colombian counsel or a notary.'
  },
  pt:{
    appName:'Evidência Jurídica',tagline:'Consulte documentos e normas com evidência verificável.',demoBadge:'Demonstração · Colômbia',
    nav:{research:'Pesquisa',documents:'Documentos',evidence:'Evidência'},
    actions:{law:'Consultar legislação',document:'Analisar um documento',ask:'Consultar',remove:'Excluir',reindex:'Reindexar',inspect:'Ver trechos',close:'Fechar',changeArea:'Mudar área',newQuery:'Nova consulta',showMore:'Mostrar mais fontes',showLess:'Mostrar menos fontes'},
    landing:{eyebrow:'Pesquisa jurídica baseada em evidências',title:'Trabalhe a partir da fonte, não de uma resposta opaca.',body:'Consulte um corpus jurídico colombiano governado e compare-o com documentos privados processados localmente nesta sessão.',areaTitle:'Em que área você está trabalhando?',areaHelp:'A área orienta a busca; não é uma classificação jurídica rígida.'},
    domains:{general:'Geral',civil:'Direito civil',familia:'Direito de família',laboral:'Direito do trabalho',penal:'Direito penal',notarial:'Direito notarial',constitucional:'Direito constitucional',unsure:'Não tenho certeza'},
    workspace:{corpus:'Corpus',corpusCount:'Fontes normativas',documents:'Documentos privados',noDocuments:'Nenhum documento foi adicionado.',question:'Consulta',questionHelp:'Faça uma pergunta concreta. A resposta usará apenas evidência que passe pelo controle de suficiência jurídica.',placeholder:'Ex.: Quais elementos a norma disponível exige para um contrato de trabalho?',sources:'Fontes e evidências',noAnswer:'As fontes aparecerão aqui após uma consulta.',emptyAnswer:'Faça uma consulta para ver resposta, fundamento e evidência.',area:'Área de pesquisa',publicCorpus:'Corpus jurídico público',privateDocs:'Documentos desta sessão'},
    coverage:{title:'Escopo desta demonstração',partial:'Corpus parcial',sources:'fontes oficiais registradas',passages:'trechos governados',jurisprudence:'Jurisprudência não incluída',fullText:'Sem textos oficiais completos locais',note:'Uma resposta sustentada significa suporte suficiente apenas dentro da evidência mostrada; não certifica que a pesquisa jurídica esteja completa.'},
    tasks:{title:'Atalhos de pesquisa',help:'Escolha uma tarefa para estruturar a consulta.',identify:'Identificar norma',proof:'Elementos e prova',deadline:'Prazo ou prescrição',competence:'Competência judicial',change:'Mudança ou versão',jurisprudence:'Jurisprudência',document:'Comparar documento',examples:{identify:'Qual norma disponível regula ',proof:'Quais elementos devem ser provados na evidência disponível sobre ',deadline:'Qual prazo ou prescrição se aplica a ',competence:'Qual juiz ou regra de competência se aplica a ',change:'O que mudou entre versões sobre ',jurisprudence:'Qual jurisprudência oficial interpreta ',document:'Compare meu documento com a regra disponível sobre '}},
    upload:{title:'Analisar um documento',body:'PDF com camada de texto, DOCX ou TXT. Máximo 10 MB.',choose:'Selecionar arquivo',local:'Processamento local nesta sessão',noTraining:'Sem rota de treinamento nem telemetria de conteúdo',retention:'Texto e vetores permanecem apenas na memória da sessão.',warning:'Para esta demonstração, não envie informações confidenciais de clientes.',stages:{preparing:'Preparando documento',reading:'Lendo texto',organizing:'Organizando seções',search_ready:'Preparando busca',ready:'Pronto para consultar'},ocr:'OCR não está implementado; PDFs sem camada de texto não podem ser indexados.'},
    evidence:{law:'Norma',user:'Documento do usuário',article:'Artigo / seção',authority:'Autoridade',verified:'Fuente consultada',version:'Versão',source:'Verificar na fonte oficial',historical:'Vigência atual não resolvida',crossDomain:'Relevante fora da área preferida',notSupport:'Relacionado; não sustenta a resposta',excerpt:'Trecho exato',score:'Diagnóstico técnico de recuperação · não é confiança jurídica'},
    answer:{supported:'Suporte suficiente no corpus disponível',supportedDetail:'A conclusão mostrada se limita à evidência governada citada abaixo. Verifique a fonte oficial antes do uso profissional.',insufficient:'Evidência insuficiente',insufficientDetail:'O sistema encontrou material relacionado, mas não evidência suficiente para responder com fundamento.',recoveryTitle:'O que falta para responder',recoveryGeneral:'Refine a consulta com fatos ou uma norma mais específica, ou amplie o corpus com autoridade oficial pertinente.',requirements:{deadline:'Falta uma regra expressa de prazo, termo, prescrição ou caducidade.',competence:'Falta uma regra expressa de competência ou foro aplicável.',remedy:'Falta uma regra que estabeleça o recurso ou meio de impugnação.',procedure:'Falta evidência processual que descreva o procedimento ou os passos aplicáveis.',change_comparison:'Faltam versões ou alterações normativas comparáveis para afirmar o que mudou.',jurisprudence:'Este corpus ainda não contém jurisprudência governada para sustentar essa resposta.',current_validity:'Não há certificação de vigência suficiente para afirmar vigência atual.',tariff:'Falta uma fonte tarifária ou fiscal atual com o valor aplicável.'}},
    status:{loading:'Preparando corpus…',ready:'Corpus pronto',error:'Não foi possível concluir a operação.',deleted:'Documento removido da sessão.',reindexed:'Documento reindexado.',uploaded:'Documento pronto para consulta.'},
    diagnostics:{title:'Diagnóstico avançado',model:'Modelo local',chunks:'Fragmentos',hash:'SHA-256',scope:'Escopo',scores:'Pontuações'},
    privacy:{title:'Privacidade da demonstração',body:'Os documentos são processados localmente e permanecem apenas na memória desta sessão. Ao excluir, texto, fragmentos e vetores são removidos; um registro não textual de exclusão pode permanecer até recarregar a página.'},
    language:'Idioma',skip:'Ir para o conteúdo',footer:'Ferramenta de pesquisa baseada em evidências. Não substitui o julgamento profissional de advogado ou notário colombiano.'
  }
});

export const uiMessages=(locale='es')=>UI_MESSAGES[locale]??UI_MESSAGES.es;
export function t(locale,path) { return path.split('.').reduce((v,k)=>v?.[k],uiMessages(locale)) ?? path; }
